.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH mirror 1  "mirror " 
.SH NAME
mirror \- Fetch and pin a blob from provider(s) to replicate content locally
.SH SYNOPSIS
\fBmirror\fR <\fB\-\-hash\fR> [\fB\-\-from\fR] [\fB\-\-min\-providers\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Fetch and pin a blob from provider(s) to replicate content locally
.SH OPTIONS
.TP
\fB\-\-hash\fR \fI<HASH>\fR
Content hash to mirror
.TP
\fB\-\-from\fR \fI<FROM>\fR
Blob ticket(s) for providers (can repeat)
.TP
\fB\-\-min\-providers\fR \fI<MIN_PROVIDERS>\fR [default: 2]
Minimum providers for healthy replication
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
