.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH publish 1  "publish " 
.SH NAME
publish \- Publish a folder, blob, or catalog
.SH SYNOPSIS
\fBpublish\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Publish a folder, blob, or catalog
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
publish\-folder(1)
Publish a folder ticket for public read access
.TP
publish\-blob(1)
Publish a content hash as an unauthenticated blob ticket
.TP
publish\-catalog(1)
Publish folder metadata to a catalog
.TP
publish\-help(1)
Print this message or the help of the given subcommand(s)
