.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH leave 1  "leave " 
.SH NAME
leave \- Leave and remove a synchronized folder
.SH SYNOPSIS
\fBleave\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFOLDER\fR> 
.SH DESCRIPTION
Leave and remove a synchronized folder
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFOLDER\fR>
Namespace ID or path to a managed folder
