.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH devices 1  "devices " 
.SH NAME
devices \- Show this device\*(Aqs Iroh and Syncthing identities
.SH SYNOPSIS
\fBdevices\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show this device\*(Aqs Iroh and Syncthing identities
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
