.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH daemon-reload 1  "daemon-reload " 
.SH NAME
daemon\-reload \- Ask the local daemon to reload configuration
.SH SYNOPSIS
\fBdaemon\-reload\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Ask the local daemon to reload configuration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
