.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH daemon-sync 1  "daemon-sync " 
.SH NAME
daemon\-sync \- Ask the local daemon to trigger synchronization
.SH SYNOPSIS
\fBdaemon\-sync\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Ask the local daemon to trigger synchronization
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
