.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH subscribe 1  "subscribe " 
.SH NAME
subscribe \- Subscribe to a folder with event filters
.SH SYNOPSIS
\fBsubscribe\fR [\fB\-\-ingest\-only\fR] [\fB\-\-ignore\-self\fR] [\fB\-\-prefix\fR] [\fB\-\-glob\fR] [\fB\-\-max\-count\fR] [\fB\-\-max\-size\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fITICKET\fR> [\fIPATH\fR] 
.SH DESCRIPTION
Subscribe to a folder with event filters
.SH OPTIONS
.TP
\fB\-\-ingest\-only\fR
Only deliver entries ingested after subscription
.TP
\fB\-\-ignore\-self\fR
Ignore events emitted by this subscription session
.TP
\fB\-\-prefix\fR \fI<PREFIX>\fR

.TP
\fB\-\-glob\fR \fI<GLOB>\fR

.TP
\fB\-\-max\-count\fR \fI<MAX_COUNT>\fR

.TP
\fB\-\-max\-size\fR \fI<MAX_SIZE>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITICKET\fR>

.TP
[\fIPATH\fR] [default: .]

