.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start 1  "start " 
.SH NAME
start \- Start the local syncweb node for one command invocation
.SH SYNOPSIS
\fBstart\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Start the local syncweb node for one command invocation
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
