.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH daemon-add 1  "daemon-add " 
.SH NAME
daemon\-add \- Add a folder to the running daemon
.SH SYNOPSIS
\fBdaemon\-add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAMESPACE\fR> <\fIPATH\fR> 
.SH DESCRIPTION
Add a folder to the running daemon
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAMESPACE\fR>

.TP
<\fIPATH\fR>

