.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH daemon-add 1  "daemon-add " 
.SH NAME
daemon\-add \- Add a folder to the running daemon
.SH SYNOPSIS
\fBdaemon\-add\fR [\fB\-\-namespace\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> 
.SH DESCRIPTION
Add a folder to the running daemon
.SH OPTIONS
.TP
\fB\-\-namespace\fR \fI<NAMESPACE>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>

