.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH stats 1  "stats " 
.SH NAME
stats \- Show statistics for folders, files, and seeding status
.SH SYNOPSIS
\fBstats\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Show statistics for folders, files, and seeding status
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
stats\-network(1)
Show persisted bandwidth accounting
.TP
stats\-files(1)
Show file\-level statistics for synced folder content
.TP
stats\-seeding(1)
Show seeding status per folder blob
.TP
stats\-help(1)
Print this message or the help of the given subcommand(s)
