.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH verify 1  "verify " 
.SH NAME
verify \- Re\-check local folder blob integrity
.SH SYNOPSIS
\fBverify\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Re\-check local folder blob integrity
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

