.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sort 1  "sort " 
.SH NAME
sort \- Sort local files by discovery criteria
.SH SYNOPSIS
\fBsort\fR [\fB\-\-by\fR] [\fB\-\-threads\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Sort local files by discovery criteria
.SH OPTIONS
.TP
\fB\-\-by\fR \fI<BY>\fR [default: niche]

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
niche
.IP \(bu 2
frecency
.IP \(bu 2
peers
.IP \(bu 2
random
.IP \(bu 2
folder
.RE
.TP
\fB\-\-threads\fR \fI<THREADS>\fR [default: 0]
Scanner threads (1 disables parallelism, 0 uses all available CPUs)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

