.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH download 1  "download " 
.SH NAME
download \- Download folder content or copy a local file
.SH SYNOPSIS
\fBdownload\fR [\fB\-\-max\-peers\fR] [\fB\-\-min\-peers\fR] [\fB\-\-min\-count\fR] [\fB\-\-max\-count\fR] [\fB\-\-threads\fR] [\fB\-\-hash\fR] [\fB\-\-from\fR] [\fB\-\-no\-sharing\fR] [\fB\-\-min\-providers\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISOURCE\fR> [\fIDESTINATION\fR] 
.SH DESCRIPTION
Download folder content or copy a local file
.SH OPTIONS
.TP
\fB\-\-max\-peers\fR \fI<MAX_PEERS>\fR
Fetch only blobs with at most N observed peers
.TP
\fB\-\-min\-peers\fR \fI<MIN_PEERS>\fR
Fetch only blobs with at least N observed peers
.TP
\fB\-\-min\-count\fR \fI<MIN_COUNT>\fR
Minimum number of blobs to fetch
.TP
\fB\-\-max\-count\fR \fI<MAX_COUNT>\fR
Maximum number of blobs to fetch
.TP
\fB\-\-threads\fR \fI<THREADS>\fR [default: 0]
Copy threads (1 disables parallelism, 0 uses all available CPUs)
.TP
\fB\-\-hash\fR \fI<HASH>\fR
Content hash to download (single blob mode)
.TP
\fB\-\-from\fR \fI<FROM>\fR
Blob ticket(s) for providers (can repeat, requires \-\-hash)
.TP
\fB\-\-no\-sharing\fR
Do not share or seed the downloaded content
.TP
\fB\-\-min\-providers\fR \fI<MIN_PROVIDERS>\fR [default: 2]
Minimum providers for healthy replication
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISOURCE\fR>

.TP
[\fIDESTINATION\fR]

