.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ls 1  "ls " 
.SH NAME
ls \- List files in a local folder
.SH SYNOPSIS
\fBls\fR [\fB\-\-sort\fR] [\fB\-\-threads\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
List files in a local folder
.SH OPTIONS
.TP
\fB\-\-sort\fR \fI<SORT>\fR
Collect and sort output instead of streaming it
.TP
\fB\-\-threads\fR \fI<THREADS>\fR [default: 0]
Scanner threads (1 disables parallelism, 0 uses all available CPUs)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

