.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH report 1  "report " 
.SH NAME
report \- Submit a local moderation report
.SH SYNOPSIS
\fBreport\fR <\fB\-\-reason\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIRECORD\fR> 
.SH DESCRIPTION
Submit a local moderation report
.SH OPTIONS
.TP
\fB\-\-reason\fR \fI<REASON>\fR
Reason for the report
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIRECORD\fR>
Content hash or record identifier
