.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH publish 1  "publish " 
.SH NAME
publish \- Publish folder metadata to a catalog
.SH SYNOPSIS
\fBpublish\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Publish folder metadata to a catalog
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
publish\-catalog(1)
Publish folder metadata to a catalog
.TP
publish\-help(1)
Print this message or the help of the given subcommand(s)
