.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH mirror 1  "mirror " 
.SH NAME
mirror \- Mirror all blobs from a provider or network
.SH SYNOPSIS
\fBmirror\fR [\fB\-\-network\fR] [\fB\-\-min\-providers\fR] [\fB\-\-no\-sharing\fR] [\fB\-\-dry\-run\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPROVIDER\fR] 
.SH DESCRIPTION
Mirror all blobs from a provider or network
.SH OPTIONS
.TP
\fB\-\-network\fR \fI<NETWORK>\fR
Network name or ID to mirror all blobs across
.TP
\fB\-\-min\-providers\fR \fI<MIN_PROVIDERS>\fR [default: 3]
Minimum replication budget per blob (default 3)
.TP
\fB\-\-no\-sharing\fR
Skip lease announcements after mirroring
.TP
\fB\-\-dry\-run\fR
Report what would be mirrored without fetching
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPROVIDER\fR]
Provider ID (PublicKey hex) to mirror blobs from
