.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH unpublish 1  "unpublish " 
.SH NAME
unpublish \- Remove a public blob pin
.SH SYNOPSIS
\fBunpublish\fR <\fB\-\-blob\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fINAMESPACE\fR> 
.SH DESCRIPTION
Remove a public blob pin
.SH OPTIONS
.TP
\fB\-\-blob\fR \fI<BLOB>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAMESPACE\fR>

