.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH sync 1  "sync " 
.SH NAME
sync \- Ask the local daemon to trigger synchronization
.SH SYNOPSIS
\fBsync\fR [\fB\-h\fR|\fB\-\-help\fR] [\fINAMESPACE\fR] 
.SH DESCRIPTION
Ask the local daemon to trigger synchronization
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAMESPACE\fR]
Namespace of a live folder to sync now; omit it to sync every enabled folder
