.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH daemon-remove 1  "daemon-remove " 
.SH NAME
daemon\-remove \- Remove a folder from the running daemon
.SH SYNOPSIS
\fBdaemon\-remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAMESPACE\fR> 
.SH DESCRIPTION
Remove a folder from the running daemon
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAMESPACE\fR>

