.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH accept 1  "accept " 
.SH NAME
accept \- Accept a locally available folder
.SH SYNOPSIS
\fBaccept\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAMESPACE\fR> 
.SH DESCRIPTION
Accept a locally available folder
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAMESPACE\fR>

