.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH health 1  "health " 
.SH NAME
health \- Show seeding status per folder blob
.SH SYNOPSIS
\fBhealth\fR [\fB\-\-hash\fR] [\fB\-\-path\-prefix\fR] [\fB\-\-glob\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Show seeding status per folder blob
.SH OPTIONS
.TP
\fB\-\-hash\fR \fI<HASH>\fR
Content hash(es) to select (can repeat)
.TP
\fB\-\-path\-prefix\fR \fI<PATH_PREFIX>\fR
Only entries whose path starts with this prefix
.TP
\fB\-\-glob\fR \fI<GLOB>\fR
Only entries whose path matches this glob pattern
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

