.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH verify 1  "verify " 
.SH NAME
verify \- Re\-check local folder blob integrity
.SH SYNOPSIS
\fBverify\fR [\fB\-\-hash\fR] [\fB\-\-path\-filter\fR] [\fB\-\-glob\-filter\fR] [\fB\-\-fix\fR] [\fB\-\-from\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Re\-check local folder blob integrity
.SH OPTIONS
.TP
\fB\-\-hash\fR \fI<HASH>\fR
Content hash(es) to verify (can repeat)
.TP
\fB\-\-path\-filter\fR \fI<PATH_FILTER>\fR
Only verify entries whose path matches this prefix
.TP
\fB\-\-glob\-filter\fR \fI<GLOB_FILTER>\fR
Only verify entries whose path matches this glob pattern
.TP
\fB\-\-fix\fR
Attempt to repair corrupted blobs by re\-downloading from peers
.TP
\fB\-\-from\fR \fI<FROM>\fR
Blob ticket(s) for providers (can repeat, requires \-\-fix)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

