.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH init 1  "init " 
.SH NAME
init \- Initialize a folder and print a shareable URL
.SH SYNOPSIS
\fBinit\fR [\fB\-\-prefix\fR] [\fB\-\-mode\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Initialize a folder and print a shareable URL
.SH OPTIONS
.TP
\fB\-\-prefix\fR \fI<PREFIX>\fR

.TP
\fB\-\-mode\fR \fI<MODE>\fR [default: sendreceive]

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

