.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH attest 1  "attest " 
.SH NAME
attest \- Sign content provenance attestations
.SH SYNOPSIS
\fBattest\fR [\fB\-\-license\fR] [\fB\-\-provenance\fR] [\fB\-\-derivative\fR] [\fB\-\-sequence\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICONTENT\fR> 
.SH DESCRIPTION
Sign content provenance attestations
.SH OPTIONS
.TP
\fB\-\-license\fR \fI<LICENSE>\fR

.TP
\fB\-\-provenance\fR \fI<PROVENANCE>\fR
Provenance attestation type
.TP
\fB\-\-derivative\fR \fI<DERIVATIVE>\fR
Derivative work attestation type
.TP
\fB\-\-sequence\fR \fI<SEQUENCE>\fR [default: 1]

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICONTENT\fR>
Content hash to attest
