.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH download 1  "download " 
.SH NAME
download \- Download a local file to a destination
.SH SYNOPSIS
\fBdownload\fR [\fB\-\-threads\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISOURCE\fR> <\fIDESTINATION\fR> 
.SH DESCRIPTION
Download a local file to a destination
.SH OPTIONS
.TP
\fB\-\-threads\fR \fI<THREADS>\fR [default: 0]
Copy threads (1 disables parallelism, 0 uses all available CPUs)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISOURCE\fR>

.TP
<\fIDESTINATION\fR>

