.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH leave 1  "leave " 
.SH NAME
leave \- Leave a synchronized folder, optionally deleting its local files
.SH SYNOPSIS
\fBleave\fR [\fB\-\-delete\-files\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFOLDER\fR> 
.SH DESCRIPTION
Leave a synchronized folder, optionally deleting its local files
.SH OPTIONS
.TP
\fB\-\-delete\-files\fR
Also delete the folder\*(Aqs local files
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFOLDER\fR>
Namespace ID or path to a managed folder
