.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH attest 1  "attest " 
.SH NAME
attest \- Sign content provenance attestations
.SH SYNOPSIS
\fBattest\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Sign content provenance attestations
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
attest\-create(1)
Sign and optionally broadcast a content attestation
.TP
attest\-verify(1)
Verify attestations for content from the network
.TP
attest\-list(1)
List local attestations for a content hash
.TP
attest\-help(1)
Print this message or the help of the given subcommand(s)
