.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH moderation 1  "moderation " 
.SH NAME
moderation \- Manage local moderation decisions
.SH SYNOPSIS
\fBmoderation\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage local moderation decisions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
moderation\-ls(1)
List local moderation records
.TP
moderation\-hide(1)
Hide a content record locally
.TP
moderation\-help(1)
Print this message or the help of the given subcommand(s)
