.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH publish 1  "publish " 
.SH NAME
publish \- Publish a folder or blob for public read access
.SH SYNOPSIS
\fBpublish\fR [\fB\-\-blob\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAMESPACE\fR> 
.SH DESCRIPTION
Publish a folder or blob for public read access
.SH OPTIONS
.TP
\fB\-\-blob\fR \fI<BLOB>\fR
Publish this content hash as an unauthenticated blob ticket
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAMESPACE\fR>
Namespace ID or managed folder path
