.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH stop 1  "stop " 
.SH NAME
stop \- Stop the local syncweb daemon
.SH SYNOPSIS
\fBstop\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Stop the local syncweb daemon
.SH OPTIONS
.TP
\fB\-\-force\fR
Skip graceful shutdown
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
