.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH health 1  "health " 
.SH NAME
health \- Show seeding status per folder blob
.SH SYNOPSIS
\fBhealth\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Show seeding status per folder blob
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR] [default: .]

