.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH networks 1  "networks " 
.SH NAME
networks \- Show networks and their health
.SH SYNOPSIS
\fBnetworks\fR [\fB\-h\fR|\fB\-\-help\fR] [\fINAME\fR] 
.SH DESCRIPTION
Show networks and their health
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fINAME\fR]
Limit to a single network by name or ID
