.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH unwatch 1  "unwatch " 
.SH NAME
unwatch \- Stop watching a folder for local changes
.SH SYNOPSIS
\fBunwatch\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFOLDER\fR> 
.SH DESCRIPTION
Stop watching a folder for local changes
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFOLDER\fR>
Namespace ID or path to a managed folder
